server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.11.101,192.168.11.102,192.168.11.103
    port: 5672
    username: admin
    password: adcc
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: JCcccHost
