spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring?characterEncoding=utf8
    username: root
    password: AdccAdcc
  jpa:
    database: MYSQL
    show-sql: true
    #Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect