server:
  port: 9290
spring:
  activemq:
    broker-url: failover:(tcp://192.168.11.101:62616,tcp://192.168.11.102:62616)
    user:
    password:
  jms:
    pub-sub-domain: false #启用发布订阅模式（默认关闭是点对点模式）
queueName: ActiveMQ-Test_Queue
topicName: ActiveMQ-Test_Topic