spring:
  datasource:
    url: jdbc:mysql://192.168.11.101:3310/readinglist?characterEncoding=utf8
    #url: jdbc:mysql://127.0.0.1:3306/readinglist?characterEncoding=utf8
    username: root
    #password: woodcar
    #password: AdccAdcc
    password: adccadcc
  jpa:
    database: MYSQL
    show-sql: true
    #Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect