spring:
  # activemq
  activemq:
    broker-url: failover:(tcp://192.168.11.74:61616)?randomize=false      # tcp://localhost:61616/故障转移，默认情况下如果某个链接失效了，则从列表中随机获取一个，如果设置了randomize=false则是严格按照列表的先后顺序的
    #user: admin           # 用户名
    #password: admin       # 密码
    in-memory: false      # 基于内存的activemq
    close-timeout: 15s     # 在考虑结束之前等待的时间
    pool:
      enabled: true                               # 启动连接池(是否用Pooledconnectionfactory代替普通的ConnectionFactory)
      max-connections: 10                         # 最大链接数量
      idle-timeout: 60s                           # 空闲连接存活时间
      block-if-full: true                         # 当连接请求和池满时是否阻塞。设置false会抛“JMSException异常”
      block-if-full-timeout: -1                   # 如果池仍然满，则在抛出异常之前阻塞时间
      create-connection-on-startup: true          # 是否在启动时创建连接。可以在启动时用于加热池
      maximum-active-session-per-connection: 500  # 每个连接的有效会话的最大数目。
      reconnect-on-exception: true                # 当发生"JMSException"时尝试重新连接
  jms:
    pub-sub-domain: false