server:
  port: 9097
spring:
  datasource:
    url: jdbc:mysql://192.168.11.101:3308/restdemo
    data-username: root
    data-password: adccadcc
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    #查询时是否显示日志
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

