spring:
  datasource:
    # 驱动配置信息
    url: jdbc:mysql://192.168.11.102:3308/spring_boot?useUnicode=true&characterEncoding=utf8
    username: root
    password: adccadcc
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    # 连接池的配置信息
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 192.168.11.102
    port: 6479
    #password: pass1234
    pool:
      #max-idle: 10
      #max-wait: 100000
    timeout: 0
    jedis:
      pool:
        max-idle: 100
        max-wait: 100000
